check = input('Digite algo:')
print('O tipo primitivo desse valor é',type(check))
print('Só tem espaços?',check.isspace())
print('É um número?',check.isnumeric())
print('É alfabético?',check.isalpha())
print('É alfanumérico?',check.isalnum())
print('Está em maiúsculas?',check.isupper())
print('Está em minúsculas?',check.islower())
print('Está capitalizada?',check.istitle())
